### ISSUE TITLE
Can't install on arm64

### ISSUE THREAD

**Issue by babolivier** [Level/leveldown#297] opened 2016-07-22 18:26 UTC
Hi there,

As there seems to be no binary for the arm64 architecture, leveldown won't install on my [Pine64](https://www.pine64.com/) with a simple `npm install` (so as a dependencie, which is how I want to use it).

Here's some of my Node.js process variables:

```
[brendan@pine64 data-system]# node
> process.arch
'arm64'
> process.platform
'linux'
> process.versions
{ http_parser: '2.5.2',
  node: '4.4.7',
  v8: '4.5.103.36',
  uv: '1.8.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '46',
  openssl: '1.0.2h' }
> 
```

Would it be possible to have binaries built and released for this architecture?

**Comment by ralphtheninja** [comment] 2016-07-22 18:55
@babolivier Since it's linux it should be trivial to build during `npm install`. If there are no prebuilt binaries it will fallback to compiling leveldb and leveldown .cc files.

**Comment by ralphtheninja** [comment] 2016-07-22 18:56
@babolivier What kind of error message do you get? Please post the results of `npm i leveldown --verbose` to a gist and share that link.

**Comment by babolivier** [comment] 2016-07-22 19:04
Hi @ralphtheninja, here's the gist: https://gist.github.com/babolivier/441ad19444d66fc4e9b3038066ad3e9f

**Comment by babolivier** [comment] 2016-07-22 19:25
Well, sorry for reading the NPM log too quickly, this doesn't seem to happen because of the lack of a binary, but because of this:

```
../deps/leveldb/leveldb-1.18.0/port/atomic_pointer.h:211:2: error: #error Please implement AtomicPointer for this platform.
```

**Comment by ralphtheninja** [comment] 2016-07-22 19:39
Ok, so it's having problems while compiling. Unfortunately this seems to be related to the `LevelDB` c++ lib. You might want to dig around there to see if that has been fixed or not.

**Comment by babolivier** [comment] 2016-07-22 19:45
So I looked around a bit and came accross this issue I didn't see in my first search: https://github.com/Level/leveldown/issues/268

As I can guess, support for my architecture will be added in `1.19`, which hasn't been released yet. As the last version dates from 2014, I think I'll have better chances at trying to compile leveldb on my platform, so that's what I'm gonna do.

**Comment by babolivier** [comment] 2016-07-22 20:42
No success here (LevelDB having not a single build instruction doesn't help). However, I saw [this commit](https://github.com/myf/leveldown/commit/39a72408b555ab898e0c6c95c8125934870cc532) on a fork and wondered if that wouldn't be a nice idea to have it in leveldown, as a quickfix for people using an arm64 architecture while waiting for 1.19?

**Comment by No9** [comment] 2016-08-11 23:31
@babolivier So @juliangruber has landed 1.19 https://github.com/Level/leveldown/issues/298 
If you want to validate this bug against it and feedback we would be delighted to hear from you

**Comment by rvagg** [comment] 2016-08-23 11:54
Confirmed compile & test are 👍 on ARM64 for the `leveldb-1.19` branch.

**Comment by babolivier** [comment] 2016-08-23 12:06
Hi all, thanks @rvagg for testing, I just didn't have the time to test if everything was OK in the last few days.

**Closed** 2016-08-23 12:07 UTC
