### ISSUE TITLE
fails to build on freebsd 11.1

### ISSUE THREAD

**Issue by sopparus** [Level/leveldown#390] opened 2017-09-20 08:37 UTC
/usr/include/c++/v1/__config:73:2: error: "_LIBCPP_TRIVIAL_PAIR_COPY_CTOR" is no longer supported. use
      _LIBCPP_DEPRECATED_ABI_DISABLE_PAIR_TRIVIAL_COPY_CTOR instead
#error "_LIBCPP_TRIVIAL_PAIR_COPY_CTOR" is no longer supported. \
 ^
1 error generated.

**Comment by peakji** [comment] 2017-09-21 07:30
@sopparus Could you please copy and paste the full stack-trace here? We need more info to locate the error, but I think this looks familiar: https://github.com/lovell/sharp/issues/873

**Comment by sopparus** [comment] 2017-09-22 04:39
ok, this is full log https://pastebin.com/jT1S4P7r

thanks!

**Comment by sopparus** [comment] 2017-09-25 11:23
it does, but I dont see any clear solution there? leveldown has also worked fine in the past

**Comment by ralphtheninja** [comment] 2017-09-25 22:12
I have absolutely no idea what's going on here so am of no help atm.

**Comment by No9** [comment] 2017-09-27 13:57
OK @sopparus  this is a little confusing. 
The error that you pasted at the start of this issue seems to be a problem with an older version of 8.1.x version of node.js 
https://github.com/nodejs/node/issues/14076 
I have replicated the problem using node 8.1.x on FreeBSD 11.1 
However when I upgrade to node 8.5.x as per the setting on your environment I cannot recreate this issue and leveldown installs without any problems.
As 8.1 is the default in FreeBSD11.1 how did you upgrade your environment?

**Comment by sopparus** [comment] 2017-09-27 14:21
I use the precompiled package, and its version node-8.5.0 .
is it some environment variable youre talking about? ive done nothing except installing that package with pkg

**Comment by No9** [comment] 2017-09-27 15:01
ok - i'm using a vagrant 11.1 can I take it you are using - https://download.freebsd.org/ftp/releases/ISO-IMAGES/11.1/FreeBSD-11.1-RELEASE-amd64-dvd1.iso ?

**Comment by sopparus** [comment] 2017-09-27 15:07
correct

**Comment by No9** [comment] 2017-09-28 00:29
I've reproduced this with the iso - it's not a great story 
By default pkg uses quarterly which contains a node 8.1.4 which is known to be broken as per the nodejs/node#14076
So I modified `/etc/pkg/FreeBSD.conf` to `latest` 
Did `pkg update` `pkg install npm node` and that installed 8.5.0  
`npm install leveldown` still produces the issue above

This is due to the common.gypi being incomplete for node.js 8.x on 11.1 FreeBSD
From the error it looks like _LIBCPP_TRIVIAL_PAIR_COPY_CTOR is still being applied even though llvm >= 4.0
A quick fix is to modify the FreeBSD clause at the bottom of `~/.node-gyp/8.5.0/include/node/common.gypi` to look like this
```
 ['OS=="freebsd"', {
   'ldflags': [
     '-Wl,--export-dynamic',
   ],
 }]
```
N.B. This work around will only work after a binary build has been attempted as `~/.node-gyp` is created during that process whether it is successful or not. 
In the mean time I will try and get a long term fix as this will impact most binary builds on FreeBSD 11.1
cc @bradleythughes

**Comment by sopparus** [comment] 2017-09-28 07:18
thank you, that work around did the trick.

**Comment by sopparus** [comment] 2017-09-28 10:47
Probably this then https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=222153

THanks everyone for the help

**Comment by No9** [comment] 2017-09-28 13:13
Thanks @sopparus That looks like it should work alright - It's basically generating a config.gypi based on the current system rather than the system that node was built on. FWIW I put the reasons why that is happening in this issue https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220983#c3 

If everyone is happy maybe we close this issue?

**Closed** 2017-09-28 17:59 UTC

**Comment by tsvetomir** [comment] 2017-12-08 16:56
Can we add a pre-built node binding to the release? It's trivial to build it using the workaround suggested by @No9 and it will save everyone the trouble.

I'll leave [leveldown-v2.1.1-node-v57-freebsd-x64.tar.gz](https://github.com/Level/leveldown/files/1543311/leveldown-v2.1.1-node-v57-freebsd-x64.tar.gz) here just in case.
