### ISSUE TITLE
prebuild for raspberry pi?

### ISSUE THREAD

**Issue by robinpaulson** [Level/leveldown#345] opened 2017-02-20 02:59 UTC
I installed leveldown from npm today and got this:

prebuild-install info begin Prebuild-install version 2.1.0
prebuild-install info looking for local prebuild @ prebuilds/leveldown-v1.6.0-node-v51-linux-arm.tar.gz
prebuild-install info looking for cached prebuild @ /home/pi/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.6.0-leveldown-v1.6.0-node-v51-linux-arm.tar.gz
prebuild-install http request GET https://github.com/level/leveldown/releases/download/v1.6.0/leveldown-v1.6.0-node-v51-linux-arm.tar.gz
prebuild-install http 404 https://github.com/level/leveldown/releases/download/v1.6.0/leveldown-v1.6.0-node-v51-linux-arm.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=7.5.0 runtime=node arch=arm platform=linux)

Would it be possible to prepare a prebuild for this target? There is a prebuild for v1.5.0 bit not 1.6, according to your releases page. This wouldn't normally be a problem, but building anything non-trivial on a raspberry pi is pretty painful.

Cheers!

**Comment by farskipper** [comment] 2017-02-23 17:47
Looks like from #300 that @rvagg or @ralphtheninja have been making the arm binaries

There is a way to emulate an ARM cpu on travis-ci using QEMU
https://blog.hypriot.com/post/setup-simple-ci-pipeline-for-arm-images/
Not sure how well that will work for this, but sure would be nice.

**Comment by crzidea** [comment] 2017-06-11 03:05
There is a solution with `scaleway` (https://scaleway.com). They provide ARM servers.

**Comment by vweevers** [comment] 2018-12-26 11:04
Duplicate of #360. There's work in progress at #572.

**Closed by vweevers** 2018-12-26 11:04 UTC
