### ISSUE TITLE
createreadstream memory leak

### ISSUE THREAD

**Issue by chacent** [Level/leveldown#758] opened 2021-02-15 04:32 UTC
just use createreadstream, rss ever-increasing。process.memoryUsage is normal, so it should bug of addon

here are some logs

2021-02-15T04:31:53.932Z 2654000 {"rss":15072780288,"heapTotal":40435712,"heapUsed":4663200,"external":20221105,"arrayBuffers":17843891}
2021-02-15T04:31:54.536Z 2655000 {"rss":15078764544,"heapTotal":40435712,"heapUsed":4673936,"external":20592959,"arrayBuffers":17843891}
2021-02-15T04:31:55.157Z 2656000 {"rss":15084560384,"heapTotal":40435712,"heapUsed":4650360,"external":20206953,"arrayBuffers":17843891}
2021-02-15T04:31:55.785Z 2657000 {"rss":15090597888,"heapTotal":40435712,"heapUsed":4650472,"external":20726577,"arrayBuffers":18012169}
2021-02-15T04:31:56.362Z 2658000 {"rss":15096279040,"heapTotal":40435712,"heapUsed":4619488,"external":20324609,"arrayBuffers":17843891}
2021-02-15T04:31:56.898Z 2659000 {"rss":15101956096,"heapTotal":40435712,"heapUsed":4660632,"external":20425246,"arrayBuffers":17843891}
2021-02-15T04:31:57.461Z 2660000 {"rss":15107633152,"heapTotal":40435712,"heapUsed":4641328,"external":20507228,"arrayBuffers":17843891}
2021-02-15T04:31:58.099Z 2661000 {"rss":15114366976,"heapTotal":40435712,"heapUsed":4636512,"external":20538469,"arrayBuffers":17843891}
2021-02-15T04:31:58.668Z 2662000 {"rss":15119769600,"heapTotal":40435712,"heapUsed":4577816,"external":20400334,"arrayBuffers":17843891}
2021-02-15T04:31:59.208Z 2663000 {"rss":15125987328,"heapTotal":40435712,"heapUsed":4738712,"external":20680165,"arrayBuffers":17843891}
2021-02-15T04:31:59.760Z 2664000 {"rss":15131934720,"heapTotal":40435712,"heapUsed":4646864,"external":20713158,"arrayBuffers":17843891}
2021-02-15T04:32:00.319Z 2665000 {"rss":15137607680,"heapTotal":40435712,"heapUsed":4667328,"external":20781649,"arrayBuffers":17854017}
2021-02-15T04:32:00.909Z 2666000 {"rss":15143276544,"heapTotal":40435712,"heapUsed":4636544,"external":20398278,"arrayBuffers":17843891}
2021-02-15T04:32:01.466Z 2667000 {"rss":15148953600,"heapTotal":40697856,"heapUsed":4735376,"external":20180667,"arrayBuffers":17843891}
2021-02-15T04:32:02.027Z 2668000 {"rss":15154900992,"heapTotal":40697856,"heapUsed":4639360,"external":20305560,"arrayBuffers":17843891}
2021-02-15T04:32:02.557Z 2669000 {"rss":15160635392,"heapTotal":40697856,"heapUsed":4677584,"external":20578639,"arrayBuffers":17843891}
2021-02-15T04:32:03.125Z 2670000 {"rss":15166308352,"heapTotal":40697856,"heapUsed":4646296,"external":20774199,"arrayBuffers":17843891}
2021-02-15T04:32:03.673Z 2671000 {"rss":15171928064,"heapTotal":40435712,"heapUsed":4657224,"external":20637786,"arrayBuffers":17843891}
2021-02-15T04:32:04.189Z 2672000 {"rss":15177650176,"heapTotal":40435712,"heapUsed":4639992,"external":20514372,"arrayBuffers":17843891}
2021-02-15T04:32:04.704Z 2673000 {"rss":15183638528,"heapTotal":40435712,"heapUsed":4697072,"external":20647723,"arrayBuffers":18034136}
2021-02-15T04:32:05.302Z 2674000 {"rss":15189135360,"heapTotal":40435712,"heapUsed":4692024,"external":20613201,"arrayBuffers":17843891}
2021-02-15T04:32:05.884Z 2675000 {"rss":15195160576,"heapTotal":40435712,"heapUsed":4652792,"external":20337816,"arrayBuffers":17843891}
2021-02-15T04:32:06.462Z 2676000 {"rss":15200833536,"heapTotal":40435712,"heapUsed":4580840,"external":20510774,"arrayBuffers":17843891}
2021-02-15T04:32:07.007Z 2677000 {"rss":15206510592,"heapTotal":40435712,"heapUsed":4689552,"external":20663549,"arrayBuffers":17843891}
2021-02-15T04:32:07.623Z 2678000 {"rss":15212728320,"heapTotal":40435712,"heapUsed":4677488,"external":20428161,"arrayBuffers":17843891}
2021-02-15T04:32:08.175Z 2679000 {"rss":15218671616,"heapTotal":40435712,"heapUsed":4672336,"external":20786048,"arrayBuffers":17843891}
2021-02-15T04:32:08.738Z 2680000 {"rss":15224344576,"heapTotal":40435712,"heapUsed":4667072,"external":20596895,"arrayBuffers":17843891}
2021-02-15T04:32:09.298Z 2681000 {"rss":15230287872,"heapTotal":40435712,"heapUsed":4662224,"external":20405114,"arrayBuffers":17843891}
2021-02-15T04:32:09.864Z 2682000 {"rss":15235694592,"heapTotal":40435712,"heapUsed":4700728,"external":20507117,"arrayBuffers":17843891}
2021-02-15T04:32:10.480Z 2683000 {"rss":15241641984,"heapTotal":40697856,"heapUsed":4670408,"external":20475649,"arrayBuffers":17843891}
2021-02-15T04:32:11.060Z 2684000 {"rss":15246983168,"heapTotal":40435712,"heapUsed":4791232,"external":20611025,"arrayBuffers":17843891}
2021-02-15T04:32:11.654Z 2685000 {"rss":15252930560,"heapTotal":40435712,"heapUsed":4695232,"external":20607964,"arrayBuffers":17843891}
2021-02-15T04:32:12.255Z 2686000 {"rss":15259070464,"heapTotal":40435712,"heapUsed":4660504,"external":20575912,"arrayBuffers":17843891}
2021-02-15T04:32:12.825Z 2687000 {"rss":15266390016,"heapTotal":40435712,"heapUsed":4675024,"external":20430174,"arrayBuffers":17843891}

**Comment by chacent** [comment] 2021-02-15 04:33
```js
let counter = 0;
				for await (const {key,value} of level.createReadStream()){
					//await level2.put({ns:'company',id:key},value);
					if(++counter%1000===0) {
						await new Promise(s=>setTimeout(s,1));
						global.gc();
						console.log(new Date().toISOString(),counter,JSON.stringify(process.memoryUsage()));
					}
				}
```

**Comment by chacent** [comment] 2021-02-15 04:37
i use level module 
with the version below:
"level": "^6.0.1",
    "leveldown": "^5.6.0",
    "levelup": "^4.3.2",

**Comment by chacent** [comment] 2021-02-15 14:55
level use {writeBufferSize:512*1024*1024,maxFileSize:128*1024*1024} and the actual file size is almost 205M

**Comment by chacent** [comment] 2021-02-15 15:29
maybe maxFileSize cause this problem,the description of this parameter in the document is misleading,i will continue try

**Comment by vweevers** [comment] 2021-04-10 20:43
Could you please provide a complete example in order to reproduce, and summarize your comments?

**Comment by chacent** [comment] 2021-06-04 06:47
sorry , it's all。make single item 10k+ and on level file 100M(maxFileSize:128*1024*1024),on 64-bit, memory is uncontrolled.just set 
mmap_limit to 0 is ok

**Comment by vweevers** [comment] 2021-08-01 16:51
Closing, because without a clear problem description and example, there's no actionable item here.

**Closed by vweevers** 2021-08-01 16:51 UTC
Labels: more information needed
