### ISSUE TITLE
Assertion `dummy_versions_.next_ == &dummy_versions_' failed.

### ISSUE THREAD

**Issue by fergiemcdowall** [Level/leveldown#194] opened 2015-07-10 10:55 UTC
I've been getting this quite a lot lately. It seems to come and go at random, although probably mostly when the DB is undergoing strain

```
nodejs: ../deps/leveldb/leveldb-1.18.0/db/version_set.cc:789: leveldb::VersionSet::~VersionSet(): Assertion `dummy_versions_.next_ == &dummy_versions_' failed.
Aborted (core dumped)
```

Any tips? Is this a known bug?

**Comment by juliangruber** [comment] 2015-07-10 11:01
@ralphtheninja you helped debug this last time, i think it was something with iterators not being cleaned up, right?

**Comment by ralphtheninja** [comment] 2015-07-10 11:35
Afaik tt's related to closing the database while there are still open iterators. So the close operation have to wait until all iterators have ended before finally closing.

**Comment by fergiemcdowall** [comment] 2015-07-10 11:40
Is there some boilerplate incantation that should be used to close a DB and avoid this problem? (when using levelUp)

**Comment by juliangruber** [comment] 2015-07-11 12:28
really leveldown / levelup should handle that, it's not your fault. would it be possible for you to share a script that can cause this failure?

**Comment by fergiemcdowall** [comment] 2015-07-11 13:11
I cant reproduce it consistently. The test suite for `search-index` fails intermittently (1 in 10 times or so?) with this error (example https://travis-ci.org/fergiemcdowall/search-index/builds/70434516)

@ralphtheninja lots of closing was recently added to that test script, so your suggestion makes sense.

**Comment by ralphtheninja** [comment] 2015-07-11 13:36
It's usually also random behaviour because sometimes an operation is slightly longer or shorter depending on what the os had to do at that time. Imo this is an achilles' heel we need to addresss

**Comment by rvagg** [comment] 2015-07-12 06:27
fwiw I've never been convinced of the auto-close code for iterators, it's undergone tweaking but failures like this continue to make me suspicious

**Comment by jacargentina** [comment] 2015-09-09 16:06
Any news on this? I'm getting this error a lot when using `search-index` on my website

**Comment by nolanlawson** [comment] 2017-01-01 22:46
I'm not sure if this is the same error, but PouchDB's tests have been failing since we tried updating to leveldown 1.5.1:

```
node: ../deps/leveldb/leveldb-1.19/db/version_set.cc:789:
  leveldb::VersionSet::~VersionSet():
  Assertion `dummy_versions_.next_ == &dummy_versions_' failed.
bin/test-node.sh: line 50:  4949 Aborted (core dumped)
```

It could be that we've been using some undocumented behavior, or it could be a true failure. Haven't diagnosed yet, but the repro is:

    npm i -g pouchdb-server
    pouchdb-server -p 5984 &
    git clone https://github.com/pouchdb/pouchdb.git --branch greenkeeper-leveldown-1.5.3
    cd pouchdb
    npm it

Related: https://github.com/pouchdb/pouchdb/pull/6088 https://github.com/pouchdb/pouchdb/pull/6077

**Comment by nolanlawson** [comment] 2017-02-05 23:45
Still failing in 1.6.0: https://github.com/pouchdb/pouchdb/pull/6202 (see issue for Travis runs & logs).

**Comment by ralphtheninja** [comment] 2017-02-06 09:02
@nolanlawson Did you have any kind of problems similar to this before 1.5.1?

**Comment by nolanlawson** [comment] 2017-02-07 01:32
@ralphtheninja We are currently shipping PouchDB with leveldown@1.5.0, and all of our tests pass very solidly on that release. I haven't done a git bisect or anything yet, so I'm not sure exactly what regressed for us in 1.5.1.

**Comment by ralphtheninja** [comment] 2017-02-07 10:32
@nolanlawson I made a quick diff check (`git diff v1.5.0 v1.5.1`) and there was some work done on `src/iterator.{h,cc}` (I removed everything else from the diff that was not related to the c++ side). So there might be something in there that's not 100% ok.

cc @Level/owners 

```diff
--- a/src/iterator.cc
+++ b/src/iterator.cc
@@ -56,7 +56,9 @@ Iterator::Iterator (
   options->snapshot = database->NewSnapshot();
   dbIterator = NULL;
   count      = 0;
+  target     = NULL;
   seeking    = false;
+  landed     = false;
   nexting    = false;
   ended      = false;
   endWorker  = NULL;
@@ -64,6 +66,7 @@ Iterator::Iterator (
 
 Iterator::~Iterator () {
   delete options;
+  ReleaseTarget();
   if (start != NULL) {
     // Special case for `start` option: it won't be
     // freed up by any of the delete calls below.
@@ -171,6 +174,38 @@ bool Iterator::Read (std::string& key, std::string& value) {
   return false;
 }
 
+bool Iterator::OutOfRange (leveldb::Slice* target) {
+  if (lt != NULL) {
+    if (target->compare(*lt) >= 0)
+      return true;
+  } else if (lte != NULL) {
+    if (target->compare(*lte) > 0)
+      return true;
+  } else if (start != NULL && reverse) {
+    if (target->compare(*start) > 0)
+      return true;
+  }
+
+  if (end != NULL) {
+    int d = target->compare(*end);
+    if (reverse ? d < 0 : d > 0)
+      return true;
+  }
+
+  if (gt != NULL) {
+    if (target->compare(*gt) <= 0)
+      return true;
+  } else if (gte != NULL) {
+    if (target->compare(*gte) < 0)
+      return true;
+  } else if (start != NULL && !reverse) {
+    if (target->compare(*start) < 0)
+      return true;
+  }
+
+  return false;
+}
+
 bool Iterator::IteratorNext (std::vector<std::pair<std::string, std::string> >& result) {
   size_t size = 0;
   while(true) {
@@ -181,6 +216,11 @@ bool Iterator::IteratorNext (std::vector<std::pair<std::string, std::string> >&
       result.push_back(std::make_pair(key, value));
       size = size + key.size() + value.size();
 
+      if (!landed) {
+        landed = true;
+        return true;
+      }
+
       if (size > highWaterMark)
         return true;
 
@@ -205,7 +245,19 @@ void Iterator::Release () {
   database->ReleaseIterator(id);
 }
 
+void Iterator::ReleaseTarget () {
+  if (target != NULL) {
+
+    if (!target->empty())
+      delete[] target->data();
+
+    delete target;
+    target = NULL;
+  }
+}
+
 void checkEndCallback (Iterator* iterator) {
+  iterator->ReleaseTarget();
   iterator->nexting = false;
   if (iterator->endWorker != NULL) {
     Nan::AsyncQueueWorker(iterator->endWorker);
@@ -215,35 +267,53 @@ void checkEndCallback (Iterator* iterator) {
 
 NAN_METHOD(Iterator::Seek) {
   Iterator* iterator = Nan::ObjectWrap::Unwrap<Iterator>(info.This());
+
+  iterator->ReleaseTarget();
+
+  v8::Local<v8::Value> targetBuffer = info[0].As<v8::Value>();
+  LD_STRING_OR_BUFFER_TO_COPY(_target, targetBuffer, target);
+  iterator->target = new leveldb::Slice(_targetCh_, _targetSz_);
+
   iterator->GetIterator();
   leveldb::Iterator* dbIterator = iterator->dbIterator;
-  Nan::Utf8String key(info[0]);
 
-  dbIterator->Seek(*key);
+  dbIterator->Seek(*iterator->target);
   iterator->seeking = true;
+  iterator->landed = false;
 
-  if (dbIterator->Valid()) {
-    int cmp = dbIterator->key().compare(*key);
-    if (cmp > 0 && iterator->reverse) {
-      dbIterator->Prev();
-    } else if (cmp < 0 && !iterator->reverse) {
-      dbIterator->Next();
-    }
-  } else {
+  if (iterator->OutOfRange(iterator->target)) {
     if (iterator->reverse) {
-      dbIterator->SeekToLast();
-    } else {
       dbIterator->SeekToFirst();
+      dbIterator->Prev();
+    } else {
+      dbIterator->SeekToLast();
+      dbIterator->Next();
     }
+  }
+  else {
     if (dbIterator->Valid()) {
-      int cmp = dbIterator->key().compare(*key);
+      int cmp = dbIterator->key().compare(*iterator->target);
       if (cmp > 0 && iterator->reverse) {
-        dbIterator->SeekToFirst();
         dbIterator->Prev();
       } else if (cmp < 0 && !iterator->reverse) {
-        dbIterator->SeekToLast();
         dbIterator->Next();
       }
+    } else {
+      if (iterator->reverse) {
+        dbIterator->SeekToLast();
+      } else {
+        dbIterator->SeekToFirst();
+      }
+      if (dbIterator->Valid()) {
+        int cmp = dbIterator->key().compare(*iterator->target);
+        if (cmp > 0 && iterator->reverse) {
+          dbIterator->SeekToFirst();
+          dbIterator->Prev();
+        } else if (cmp < 0 && !iterator->reverse) {
+          dbIterator->SeekToLast();
+          dbIterator->Next();
+        }
+      }
     }
   }
 
diff --git a/src/iterator.h b/src/iterator.h
index bed53f8..07e67cd 100644
--- a/src/iterator.h
+++ b/src/iterator.h
@@ -53,6 +53,7 @@ public:
   leveldb::Status IteratorStatus ();
   void IteratorEnd ();
   void Release ();
+  void ReleaseTarget ();
 
 private:
   Database* database;
@@ -60,8 +61,10 @@ private:
   leveldb::Iterator* dbIterator;
   leveldb::ReadOptions* options;
   leveldb::Slice* start;
+  leveldb::Slice* target;
   std::string* end;
   bool seeking;
+  bool landed;
   bool reverse;
   bool keys;
   bool values;
@@ -83,6 +86,7 @@ public:
 private:
   bool Read (std::string& key, std::string& value);
   bool GetIterator ();
+  bool OutOfRange (leveldb::Slice* target);
 
   static NAN_METHOD(New);
   static NAN_METHOD(Seek);
diff --git a/test/iterator-test.js b/test/iterator-test.js
index 87db93b..49d2e2a 100644

```

**Comment by hubgit** [comment] 2017-03-30 20:59
In case it's helpful, this is the PouchDB test that's failing:

```js
    it('Closing db does not cause a crash if changes cancelled',
      function (done) {
      var db = new PouchDB(dbs.name);
      var called = 0;
      function checkDone() {
        called++;
        if (called === 2) {
          done();
        }
      }
      db.bulkDocs({ docs: [{ foo: 'bar' }] }, function () {
        var changes = db.changes({
          live: true
        }).on('complete', function (result) {
          result.status.should.equal('cancelled');
          checkDone();
        });
        should.exist(changes);
        changes.cancel.should.be.a('function');
        changes.cancel();
        db.close(function (error) {
          should.not.exist(error);
          checkDone();
        });
      });
    });
```

https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.changes.js#L2312

**Comment by vweevers** [comment] 2017-06-06 23:42
Here's a repro without pouchdb. Runs ok with leveldown 1.5.0, consistently crashes with 1.5.1.

```js
const test = require('tape')
const leveldown = require('../')
const testCommon = require('abstract-leveldown/testCommon')
const location = testCommon.location

test('close db with open iterator', function (t) {
  t.plan(4)

  const loc = location()
  const db = leveldown(loc)

  db.open(function (err) {
    t.ifError(err, 'no error from open()')

    db.put('key', 'value', function (err) {
      t.ifError(err, 'no error from put()')

      const ite = db.iterator()

      ;(function loop() {
        ite.next(function (err, key, value) {
          if (err) return t.fail(err)

          if (key === undefined) {
            t.ok(true, 'end of iterator')

            return ite.end(function (err) {
              t.ifError(err, 'no error from end()')
            })
          }

          loop()
        })
      })()

      db.close(function (err) {
        t.error(err, 'no error from close()')
      })
    })
  })
})
```

**Comment by vweevers** [comment] 2017-06-07 00:41
If anyone wants to pick this up, https://github.com/Level/leveldown/pull/329/commits/9d44401f3b7be2439dc27b36b0244704868772bd is where it breaks. /cc @peakji

**Comment by peakji** [comment] 2017-06-07 04:58
The problem was there for quite a long time but somehow hidden by `highWaterMark`, until https://github.com/Level/leveldown/commit/9d44401f3b7be2439dc27b36b0244704868772bd actually revealed it.

With the `highWaterMark` mechanism, iterator reads ahead and **Iterator::Read** ([iterator.cc#L139](https://github.com/Level/leveldown/blob/master/src/iterator.cc#L139)) will get a chance to return `false` and update status before executing the next **iterator.next()**.

![crash](https://user-images.githubusercontent.com/219051/26862397-6baa2162-4b7d-11e7-8b3d-8ecd1e20877f.jpg)

The default `highWaterMark` (**16K**) is not a small number, so the chance of reaching the end before the next `next` is quite big. In other words, @fergiemcdowall is not getting *random* errors, but lucky enough to avoid the most it 😅.

In @vweevers 's sample code above, the error can be reproduced in versions before https://github.com/Level/leveldown/commit/9d44401f3b7be2439dc27b36b0244704868772bd by setting the `highWaterMark` to **0** or any small num.

The simplest way to fix this is to ignore all `next` calls after the auto-close code marks the open iterators, I've opened a PR https://github.com/Level/leveldown/pull/368 for this, but not 100% sure about the affects. /cc @nolanlawson

**Comment by vweevers** [comment] 2017-06-07 08:18
Nice work @peakji :) That graphic explains it all

**Comment by ralphtheninja** [comment] 2017-06-07 10:57
@vweevers Awesome that you created a test for this. If you don't mind I will steal it and make a PR into @peakji 's master

**Comment by ralphtheninja** [comment] 2017-06-07 11:00
See https://github.com/peakji/leveldown/pull/1

**Comment by peakji** [comment] 2017-06-07 11:01
@ralphtheninja Actually I've already stole it 🤣: [test/iterator-test.js](https://github.com/Level/leveldown/pull/368/files#diff-155c57a0315eaa7e661e1b190e7ea520R155)

**Comment by vweevers** [comment] 2017-06-07 11:03
👍

**Closed** 2017-06-08 03:26 UTC
