### ISSUE TITLE
`npm install --build-from-source` fails on io.js v3.3.0

### ISSUE THREAD

**Issue by ggreer** [Level/leveldown#218] opened 2015-09-04 01:49 UTC
I'm not sure if this is the fault of prebuild or node-gyp or what, but building from source can't seem to find common.gypi. [Here's the output](https://gist.github.com/ggreer/e4c2546294ccf68e63d7) of `npm install --build-from-source --verbose` with leveldown master on OS X 10.10.5, using io.js v3.3.0. I've had the same behavior using io.js v3.3.0 on Ubuntu 14.04.3.

I've worked-around the problem by specifying `--nodedir`. Unfortunately, `--nodedir` must be the directory of a node/io.js build, not `/usr/local/include/node`. In my case, leveldown builds if I run `npm install --build-from-source --verbose --nodedir=~/Downloads/iojs-v3.3.0`

Please let me know if you need any more information.

**Comment by ggreer** [comment] 2015-09-04 01:51
I forgot to mention: debug builds fail. Here's the output on my system: https://gist.github.com/5541bf810a4e807bf9e0

I'm pretty sure it's due to [prebuild hard-coding `build/Release`](https://github.com/mafintosh/prebuild/blob/master/build.js#L9)

**Comment by ralphtheninja** [comment] 2015-09-04 02:06
If there's something wrong with the current `node-gyp` setup you could try:

```
$ rm ~/.node-gyp/3.3.0 -rf
$ npm i --build-from-source
```

alternatively:

```
$ rm ~/.node-gyp/3.3.0 -rf
$ npm i node-gyp-isntall -g
$ node-gyp-install
$ npm i --build-from-source
```

**Comment by ggreer** [comment] 2015-09-05 02:32
Removing `~/.node-gyp/3.3.0` fixes this. Sorry for the incorrect bug report.

The problem only happens if I first install https://github.com/bnoordhuis/node-heapdump. That creates `~/.node-gyp/3.3.0` without `common.gypi`.

Try this in your leveldown directory:

    rm -fr ~/.node-gyp/3.3.0
    npm install heapdump
    npm install --build-from-source

I'm not sure where to file this bug. It's not really the fault of either package, just poor interaction between them.

**Comment by rvagg** [comment] 2015-09-05 03:29
FWIW, all of this drama will all go away very soon, https://github.com/nodejs/node-gyp/pull/711 is going to land in Node v4 next week and will upstream to npm proper shortly thereafter doing away with all of the necessary io.js-related node-gyp hacks.

**Comment by ralphtheninja** [comment] 2015-09-05 10:21
> Removing ~/.node-gyp/3.3.0 fixes this. Sorry for the incorrect bug report.

@ggreer No worries. This is why it's important to post these issues on GitHub so we can figure out what the problem is

I don't think this is related to `heapdump` per se but rather installing *any* native module. I believe that it's actually `node-gyp` that creates `~/.node-gyp/3.3.0` incorrectly by copying include files related to the current host version of node, doing `npm i --build-from-source --verbose` in your final step gives me this output https://gist.github.com/ralphtheninja/de1e2ccd1d90bc834454#file-leveldown-issue-218-log-L144

We could try mending this in `prebuild` [here](https://github.com/ralphtheninja/prebuild/blob/7d2cb0969779a71002eddd52b44a2fbb56545409/build.js#L10) by issuing an extra call to `node-gyp-install` using `{ force: true }` *if* the build fails (or rather try `nodeGyp()` and if *that* fails then do `install({ log: opts.log, version: version, force: true })`) similarly to what we do when getting the abi version [here](https://github.com/ralphtheninja/prebuild/blob/7d2cb0969779a71002eddd52b44a2fbb56545409/abi.js#L20-L25)

`node-gyp-install` does not check for `~/.node-gyp/x.y.z/common.gypi`, but rather `installVersion` [here](https://github.com/mafintosh/node-gyp-install/blob/master/index.js#L38-L43) and calls back with no error, so `prebuild` thinks everything in order [here](https://github.com/ralphtheninja/prebuild/blob/7d2cb0969779a71002eddd52b44a2fbb56545409/build.js#L11), so another option could be to fix it in `node-gyp-install` which could check for `common.gypi` as well.

cc @mafintosh

**Comment by mafintosh** [comment] 2015-09-05 10:26
@ralphtheninja checking for common.gypi in [node-gyp-install](https://github.com/mafintosh/node-gyp-install) as well sounds like a good fix.

**Comment by ralphtheninja** [comment] 2015-09-05 10:26
@ggreer I just tried reproducing this using something else than `heapdump` and took `buffertools` instead and it's the same problem there

```
$ rm ~/.node-gyp/3.3.0 -rf
$ npm i buffertools
$ npm i --build-from-source --verbose
```

**Comment by ralphtheninja** [comment] 2015-09-05 10:26
@mafintosh Cool. I can make a PR.

**Comment by rvagg** [comment] 2015-09-05 10:45
Hey @ralphtheninja & @mafintosh, something to be aware of is that you'll need a double check because it can now be in an alternate location: https://github.com/rvagg/node-gyp/blob/process.release/lib/configure.js#L305-L309

Going forward, node-gyp will be downloading a headers-only tarball and it'll unpack most of its contents into the .node-gyp directory like so: ~/.node-gyp/version/include/node/ like a normal set of header files should. But this means that common.gypi will be in there as well. We've been shipping header tarballs since `3.0.0`. Of course for versions `<3.0.0` it'll still want the full source tarball.

Another factor for node-gyp-install is that node-gyp will be prefixing the versioned directories `iojs` with `iojs-`, then anything with `process.release.name != 'node'` will also be prefixed with whatever `process.release.name` is. At the moment a simple rule would be if `process.version` `>= 1.0.0 <4.0.0` then the directory will be `iojs-x.y.z`.

Complicating this however is that the node-gyp we've shipped with previous io.js versions will just stick them in `x.y.z` and use them from there, and all standard versions of node-gyp prior to now will just look them up by `process.version` which is why node-gyp-install can work.

We've released 4.0.0 RC 1 ([here](https://nodejs.org/download/rc/v4.0.0-rc.1/) with a bundled version of node-gyp that is not what you get with npm, like we've done with io.js in the past and v4.0.0 proper will also do the same. _But_, we'll be releasing a 3.0.0 of node-gyp as soon as the RC testing gives us confidence that it's doing the right thing and npm@2 will likely start bundling it shortly after that and it'll become standard(ish).

Food for thought, sorry for the complexity but it's for the best, honest .. Hit me up if you have any quesitons.

Also /cc @springmeyer: this context might be interesting for you too.

**Comment by ralphtheninja** [comment] 2015-09-05 10:48
@rvagg Thanks for the heads up. Mind creating an issue on `node-gyp-install` and link to this issue?

**Closed** 2015-09-05 11:18 UTC

**Comment by ralphtheninja** [comment] 2015-09-05 11:23
@ggreer Please test again and close this issue if it works out for you.

**Comment by ggreer** [comment] 2015-09-05 17:30
It works. Thanks for fixing this.
