### ISSUE TITLE
Leveldown: no native build was found

### ISSUE THREAD

**Issue by killpowa** [Level/leveldown#747] opened 2020-10-26 16:32 UTC
# Bug report
I am trying to create a production executable with `electron-builder`. My issue is with the module `leveldown`.
When using webpack and creating a production release, I get the following error. Without using webpack it works and it works in dev too, with and without webpack. The issue is only happening in production with webpack.
I read that adding `leveldown` to the externals solved this issue for some people, but doing so will result in `cannot find module: leveldown` for me.

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/10165264/97194329-50a80580-17aa-11eb-9479-b517f152eb97.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
 You can find a minimal reproduction repo here: https://github.com/killpowa/leveldown-issue-repo.
Just run `npm i`, `npm run build` and `npm run pack`.

**What is the expected behavior?**
I am not sure what the problem is, I guess some config for `leveldown` specifically, because the repo also has `nsfw` which is another native module, which works just fine.

**Other relevant information:**
webpack version:  5.2.0
Node.js version: 14.13.0
Operating System: Windows 10 x64

**Comment by vweevers** [comment] 2020-10-26 17:06
Add it to files here: https://github.com/killpowa/leveldown-issue-repo/blob/335465faf11498d03ad1c8864c944b2dda99999e/package.json#L14-L20. You may also need asarUnpack:

```js
"build": {
  "files": [
    "!node_modules/**/*",
    "node_modules/nsfw/**/*",
    "**/node_modules/leveldown/prebuilds/**/*"
    "build/**/*",
    "public/**/*"
  ],
  "asarUnpack": [
    "**/node_modules/leveldown/prebuilds/**/*"
  ]
}
```

**Comment by killpowa** [comment] 2020-10-27 00:45
I tried your solution but sadly the issue is still the same. Even though I'm instructing it to include the prebuilds, when I go check inside the unpacked app.asar, the leveldown binary is still not there

**Comment by vweevers** [comment] 2020-10-31 09:47
Try moving `level` from `devDependencies` to `dependencies`. It seems that `electron-builder` excludes it otherwise.

**Comment by ikreymer** [comment] 2020-11-12 21:10
I ran into this issue as well, and solved it by copying the `prebuilds` directory in the root of the app, by adding:

```
"build": {
  "files": [
    ...
      {
        "from": "node_modules/leveldown/prebuilds/${platform}-${arch}",
        "to": "prebuilds/${platform}-${arch}"
      }
    ]
 }
```

I am also disabling __dirname and __filename, as that's needed for other parts of the electron app to load:

```
  node: {
    __dirname: false,
    __filename: false,
  },
```

Hope this helps!

**Comment by vweevers** [comment] 2020-11-13 07:31
@ikreymer Thanks! That's a reasonable alternative as long as you don't have other native addons (with conflicting filenames).

@killpowa Seeing as the issue is with webpack & electron-builder and solutions have been offered, there's no actionable item for us and I'm closing this.

**Closed by vweevers** 2020-11-13 07:31 UTC

**Comment by raphael10-collab** [comment] 2021-02-04 15:14
@ikreymer 

What's wrong with this webpack configuration?

    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
    const CopyPlugin = require('copy-webpack-plugin');
    const webpack = require('webpack');

    module.exports = [
      new ForkTsCheckerWebpackPlugin(),
      new webpack.ExternalsPlugin('commonjs', [
       'electron'
      ]),
      new webpack.ExternalsPlugin("commonjs", [
        'leveldown'
      ]),
      new CopyPlugin({
        patterns: [
          { from: 'node_modules/leveldown/prebuilds/linux-x64', to: 'prebuilds/linux-x64' },
        ],
      }),
    ];

**Comment by raphael10-collab** [comment] 2021-02-16 13:17
@vweevers I'm having the same issue. Can I ask you to help me?

my package.json :   

      "main": "./dist/main.bundle.js",
      "private": true,
      "scripts": {
        "babel": "babel ./src/**/* -d dist",
        "lint": "cross-env NODE_ENV=development eslint . --cache --ext .js,.jsx,.ts,.tsx",
        "lint:fix": "yarn run lint -- --fix",
        "dev": "rimraf ./dist && cross-env NODE_ENV=development webpack --config ./webpack.config.js --watch --progre$
        "prod": "rimraf ./dist && cross-env NODE_ENV=production webpack --config ./webpack.config.js --progress --col$
        "start": "electron ./dist/main.bundle.js",
        "package": "rm -rf dist && yarn build && electron-builder build --publish never",
        "clean": "rimraf ./dist",
        "postinstall": "yarn electron-rebuild",
        "check-type": "tsc -w"
      },
      "build": {
        "files": [
          {
            "from": "node_modules/leveldown/prebuilds/${platform}-${arch}",
            "to": "prebuilds/${platform}-${arch}"
          }
       ],



my webpack.config.js  :   


    const lodash = require('lodash');
    const CopyPlugin = require('copy-webpack-plugin');
    const HtmlWebpackPlugin = require('html-webpack-plugin');
    const path = require('path');

    function srcPaths(src) {
      return path.join(__dirname, src);
    }

    const isEnvProduction = process.env.NODE_ENV === 'production';
    const isEnvDevelopment = process.env.NODE_ENV === 'development';

    // #region Common settings
    const commonConfig = {
      devtool: isEnvDevelopment ? 'source-map' : false,
      mode: isEnvProduction ? 'production' : 'development',
      output: { path: srcPaths('dist') },
      node: {
        __dirname: false,
        __filename: false
      },
      resolve: {
        alias: {
          _: srcPaths('src'),
          _main: srcPaths('src/main'),
          _models: srcPaths('src/models'),
          _public: srcPaths('public'),
          _renderer: srcPaths('src/renderer'),
          _cpp: srcPaths('src/cpp'),
          _python: srcPaths('src/python'),
        },
        extensions: ['.js', '.json', '.ts', '.tsx', '.cpp', '.c', '.py'],
      },
      externals: [/node_modules/, 'bufferutil', 'utf-8-validate', 'leveldown'],
      module: {
        rules: [
          {
            test: /\.(ts|tsx)$/,
            exclude: /node_modules/,
            loader: 'ts-loader',
          },
          {
            test: /\.(scss|css)$/,
            use: ['style-loader', 'css-loader'],
          },
          {
            test: /\.(jpg|png|svg|ico|icns)$/,
            loader: 'file-loader',
            options: {
              name: '[path][name].[ext]',
            },
          },
        ],
      },
   };
    // #endregion

    const mainConfig = lodash.cloneDeep(commonConfig);
    mainConfig.entry = './src/main/main.ts';
    mainConfig.target = 'electron-main';
    mainConfig.output.filename = 'main.bundle.js';
    mainConfig.plugins = [
      new CopyPlugin({
        patterns: [
          {
            from: 'package.json',
            to: 'package.json',
            transform: (content, _path) => { // eslint-disable-line no-unused-vars
              const jsonContent = JSON.parse(content);

              delete jsonContent.devDependencies;
              delete jsonContent.scripts;
              delete jsonContent.build;

              jsonContent.main = './main.bundle.js';
              jsonContent.scripts = { start: 'electron ./main.bundle.js' };
              jsonContent.postinstall = 'electron-builder install-app-deps';

               return JSON.stringify(jsonContent, undefined, 2);
            },
          },
        ],
      }),
    ];

    const rendererConfig = lodash.cloneDeep(commonConfig);
    rendererConfig.entry = './src/renderer/index.js';
    rendererConfig.target = 'electron-renderer';
    rendererConfig.output.filename = 'renderer.bundle.js';
    rendererConfig.plugins = [
      new HtmlWebpackPlugin({
        template: path.resolve(__dirname, './public/index.html'),
      }),
    ];

     module.exports = [mainConfig, rendererConfig];


After followind the indications above I get: `leveldown is not defined`

    (base) marco@pc01:~/webMatters/electronMatters/Raphy-Template$ yarn start
    yarn run v1.22.5
    $ electron ./dist/main.bundle.js
    ReferenceError: leveldown is not defined
        at Object.leveldown (/home/marco/webMatters/electronMatters/Raphy-Template/dist/main.bundle.js:245221:18)
        at __webpack_require__ (/home/marco/webMatters/electronMatters/Raphy-Template/dist/main.bundle.js:245400:42)
        at Object../node_modules/level/level.js (/home/marco/webMatters/electronMatters/Raphy-Template
    /dist/main.bundle.js:130939:111)
        at __webpack_require__ (/home/marco/webMatters/electronMatters/Raphy-Template/dist/main.bundle.js:245400:42)
        at new LevelDatastore (/home/marco/webMatters/electronMatters/Raphy-Template/dist/main.bundle.js:62289:23)
        at Object.createBackend [as create] (/home/marco/webMatters/electronMatters/Raphy-Template
    /dist/main.bundle.js:111636:10)
        at IpfsRepo.open (/home/marco/webMatters/electronMatters/Raphy-Template/dist/main.bundle.js:112320:33)
        at async openRepo (/home/marco/webMatters/electronMatters/Raphy-Template/dist/main.bundle.js:107190:7)
        at async loadRepo (/home/marco/webMatters/electronMatters/Raphy-Template/dist/main.bundle.js:107162:21)
        at async Function.start (/home/marco/webMatters/electronMatters/Raphy-Template/dist/main.bundle.js:107146:41)

How to solve the problem?

**Comment by djfm** [comment] 2022-02-07 21:37
For me, the fix was adding:

```
node: {
  __dirname: true,
}
```

to my webpack configuration
