### ISSUE TITLE
ARMv8 AARCH64 build fails

### ISSUE THREAD

**Issue by myf** [Level/leveldown#268] opened 2016-04-04 21:17 UTC
trying to install leveldown on an odroid c2 board . Archlniux is installed with `aarch64` architecture. The build process failed with the following error:

```
../deps/leveldb/leveldb-1.18.0/port/atomic_pointer.h:211:2: error: #error Please implement AtomicPointer for this platform.
 #error Please implement AtomicPointer for this platform.
```

It seems that leveldb on this architecture is not implemented. However, looking at the leveldb code at https://github.com/google/leveldb/blob/master/port/atomic_pointer.h it seems that `ARCH_CPU_ARM64_FAMILY` is defined. I was also able to install leveldb-1.18-2-aarch64 successfully from archlinux repo.

please inspect if it's leveldb's version or something else

**Comment by myf** [comment] 2016-04-04 21:39
i think i answered my own question. The leveldb repo master do have support for `aarch64`. There were two commits after the release of `1.18` [this one](https://github.com/google/leveldb/commit/c4c38f9c1f3bb405fe22a79c5611438f91208d09) provides `aarch64` support and [this one](https://github.com/google/leveldb/commit/ceff6f12152785a54885a47db349a6d8dfd0ce2c) provides `MIPS` support.

do we wait till the release of `1.19` to get these support or update them before that?

**Comment by vweevers** [comment] 2018-12-26 11:13
Duplicate of #297.

We've upgraded to LevelDB 1.19 in `leveldown@1.5.0` and to LevelDB 1.20 in `leveldown@1.7.0`.

Also, prebuilt binaries are in the works! See #360 and #572.

**Closed by vweevers** 2018-12-26 11:13 UTC
