### ISSUE TITLE
pre-build and Electron (atom-shell)

### ISSUE THREAD

**Issue by sergiovilar** [Level/leveldown#190] opened 2015-06-08 21:49 UTC
Hi guys, sorry to bother you with that matter.

I'm trying to use and distribute an Electron app that uses leveldown and levelup.

I've done a rebuild using previous versions of leveldown and levelup:

```set HOME=~/.electron-gyp && node-gyp rebuild --target=0.27.2 --arch=x64 --dist-url=https://atom.io/download/atom-shell```

This works fine on my Mac but when I try to distribute to other platforms like Linux I got this error:

```[LevelUPError: Could not locate LevelDOWN, try `npm install leveldown`]```

Ok, of course I'm missing something, I just don't know what is.

I know that versions after 1.2.2 support pre-build binaries, maybe I can use this? I've installed the latest versions of levelup and leveldown but I receive this:

```[LevelUPError: Could not locate LevelDOWN, try `npm install leveldown`]```

So, I tried to rebuild. No success at all.

```gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp```

I really don't know what to do, can someone help me?

**Comment by ralphtheninja** [comment] 2015-06-08 22:29
Of course we can try to help you, but we need more information. "I've installed the latest versions of levelup and leveldown" doesn't say exactly what you did. Is there any way you can provide more detailed information? What does your package.json look like, what does the install command look like?

**Comment by sergiovilar** [comment] 2015-06-09 02:02
@ralphtheninja thank you! Sure, this is how my package.json looks like:

```
{
  "main": "index.js",
  "name": "App name",
  "description": "App description",
  "version": "1.3.2",
  "keywords": [
    "Hackhands",
    "desktop"
  ],
  "scripts": {
    "start": "electron ./ --dev=true",
    "package": "node pkg.js",
    "package-all": "node pkg.js --all",
    "rebuild-leveldb": "cd node_modules/leveldown && set HOME=~/.electron-gyp && node-gyp rebuild --target=0.27.2 --arch=x64 --dist-url=https://atom.io/download/atom-shell"
  },
  "dependencies": {
    "adm-zip": "~0.4.4",
    "auto-launch": "~0.1.14",
    "chmodr": "~0.1.0",
    "del": "~0.1.2",
    "firebase": "~2.1.2",
    "http": "0.0.0",
    "is-online": "^4.0.2",
    "leveldown": "^1.2.2",
    "levelup": "^1.2.0",
    "log": "~1.4.0",
    "mediator-js": "~0.9.8",
    "merge": "^1.2.0",
    "moment": "^2.9.0",
    "ncp": "^0.5.1",
    "raven": "~0.7.2",
    "request": "~2.36.0",
    "semver": "^3.0.1",
    "socket.io-client": "~1.3.5",
    "winston": "~0.8.3",
    "wrench": "~1.5.8"
  },
  "devDependencies": {
    "electron-packager": "^4.1.2",
    "electron-prebuilt": "^0.27.2",
    "electron-rebuild": "^0.2.2",
    "rimraf": "^2.4.0",
    "shelljs": "^0.5.1"
  }
}
```

**Comment by sergiovilar** [comment] 2015-06-09 02:04
@ralphtheninja I ran just a `npm install levelup leveldown --save`.

**Comment by ralphtheninja** [comment] 2015-06-09 08:53
Ok cool. Mind posting the complete output of the command `npm i levelup leveldown --verbose`? Preferrably in a gist.

**Comment by sergiovilar** [comment] 2015-06-09 12:10
Sure, here it is:
https://gist.github.com/sergiovilar/d32b9ce9dd1530f4c05a

**Comment by ralphtheninja** [comment] 2015-06-09 13:01
@sergiovilar Hmm, but that seemed to work, no?

**Comment by ralphtheninja** [comment] 2015-06-09 13:04
```
[0m[37m[40mnode-pre-gyp[0m [0m[32minfo[0m [0m[35mcheck[0m checked for "/Users/sergiovilar/hh/plugin-desktop/public/node_modules/leveldown/build-pre-gyp/leveldown.node" (not found)
[0m[37m[40mnode-pre-gyp[0m [0m[32m[40mhttp[0m [0m[35mGET[0m https://github.com/level/leveldown/releases/download/v1.2.2/leveldown-v1.2.2-node-v14-darwin-x64.tar.gz
[0m[37m[40mnode-pre-gyp[0m [0m[32m[40mhttp[0m [0m[35m200[0m https://github.com/level/leveldown/releases/download/v1.2.2/leveldown-v1.2.2-node-v14-darwin-x64.tar.gz
[0m[37m[40mnode-pre-gyp[0m [0m[32minfo[0m [0m[35minstall[0m unpacking leveldown.node
[0m[37m[40mnode-pre-gyp[0m [0m[32minfo[0m [0m[35mtarball[0m done parsing tarball
[0m[37m[40mnode-pre-gyp[0m [0m[32minfo[0m [0m[35mvalidate[0m Running test command: '/usr/local/Cellar/node/0.12.2_1/bin/node --eval 'require(\'/Users/sergiovilar/hh/plugin-desktop/public/node_modules/leveldown/build-pre-gyp/leveldown.node\')''
[0m[leveldown] Success: "/Users/sergiovilar/hh/plugin-desktop/public/node_modules/leveldown/build-pre-gyp/leveldown.node" is installed via remote
```

**Comment by sergiovilar** [comment] 2015-06-09 14:37
The installation, yes, but when I try to use:

```javascript
var levelup = require('levelup')
    , path = require('path')
    , that = this;

  var storage = [];

  levelup(path.join(_path, 'App.db'), {
    valueEncoding: 'json',
    createIfMissing: true,
  }, function(err, _db){
    
    // TODO: Add repair
    if(err) console.log(err);
    db = _db;

    db.get('config', function (err, value) {
      if (err)
        storage = {};
      else
        storage = value;
      that.ready();
    });

  }); 
```

I receive:

```[LevelUPError: Could not locate LevelDOWN, try `npm install leveldown`]```

**Comment by ralphtheninja** [comment] 2015-06-09 14:44
Gotcha. Do you get this error when running in a "normal" node setting or does it happen only when running with atom-shell?

**Comment by ralphtheninja** [comment] 2015-06-09 14:57
I just ran your script (with some modifications to make it work on my machine) and it works fine for me.

```js
var levelup = require('levelup')
    , path = require('path')

  var storage = [];

  levelup(path.join(__dirname, 'App.db'), {
    valueEncoding: 'json',
    createIfMissing: true
  }, function(err, db){

    if (err) console.log(err);

    db.put('config', 'value', function (err) {
      db.get('config', function (err, value) {
        console.log('got value', value)
        if (err)
          storage = {};
        else
          storage = value;
      });
    });
  })
```

The error message you get is from an older version of `levelup` which doesn't make sense since you just installed `levelup@1.2.0`

**Comment by sergiovilar** [comment] 2015-06-09 15:13
@ralphtheninja I only tried with atom-shell but I can try with a "normal" node to see what happens.

**Comment by sergiovilar** [comment] 2015-06-09 15:16
@ralphtheninja in a "normal" node works fine.

**Comment by ralphtheninja** [comment] 2015-06-09 16:10
So what are the steps to reproduce this with `atom-shell`?

**Comment by sergiovilar** [comment] 2015-06-09 16:26
@ralphtheninja Easy:

Install electron prebuilt:

```sudo npm install -g electron-prebuilt```

Create a directory and the index.js inside with the content you modified (and install level, of course):

```javascript
var levelup = require('levelup')
    , path = require('path')

  var storage = [];

  levelup(path.join(__dirname, 'App.db'), {
    valueEncoding: 'json',
    createIfMissing: true
  }, function(err, db){

    if (err) console.log(err);

    db.put('config', 'value', function (err) {
      db.get('config', function (err, value) {
        console.log('got value', value)
        if (err)
          storage = {};
        else
          storage = value;
      });
    });
  })
```

Enter the directory and run:

```electron ./```

**Comment by ralphtheninja** [comment] 2015-06-09 16:43
Cool. I got the error now. What is your output of:

```
$ node -v
$ electron -v
```

**Comment by sergiovilar** [comment] 2015-06-09 16:46
Node: v0.12.2
Electron: v0.26.1

**Comment by ralphtheninja** [comment] 2015-06-09 16:49
Try the following please:

* install node 0.12.4
* install electron-prebuilt 0.26.2 (the latest version)
* `rm node_modules && npm i levelup leveldown`

**Comment by sergiovilar** [comment] 2015-06-09 17:21
@ralphtheninja done!

When I run using node, everything works fine but when I run electron `electron ./` I got the same error:
LevelUPError: Could not locate LevelDOWN, try `npm install leveldown`.

The latest version of electron-prebuilt is 0.27.2, right?

**Comment by ralphtheninja** [comment] 2015-06-09 17:29
@sergiovilar Yes that's correct. Sorry if I'm causing a lot of work for you. Just trying to iron out where things go wrong. Working on a PR so we can get better error messages when trying to require `leveldown`. It's clearly there, so doing `npm install leveldown` is not very helpful in this case :)

**Comment by ralphtheninja** [comment] 2015-06-10 17:40
@sergiovilar PR merged in `levelup` for better error message. If you try reinstalling it we should get more information on what's going wrong (I suspect we will get ABI error message now)

**Comment by sergiovilar** [comment] 2015-06-10 18:04
@ralphtheninja I'm now receiving this when running with Electron:

```App threw an error when running [LevelUPError: Failed to require LevelDOWN (Module version mismatch. Expected 43, got 14.). Try `npm install leveldown` if it's missing]```

**Comment by ralphtheninja** [comment] 2015-06-10 20:00
Right, which was what I expected. So `14` corresponds to `v0.12.4` and I guess `43` corresponds to current `electron` and this is why you need to rebuild the binaries.

I think @mafintosh might know more of what's going on here.

**Comment by mafintosh** [comment] 2015-06-10 20:09
The problem is that you are using using a different version of node when running npm and building leveldown / installing prebuilds, than electron is using when running your app.

This is because electron bundles their own version of node and why you need to rebuild leveldown using the electron header files after installing it (the same goes for installing any other native module for that sake). Prebuilds cannot really solve this.

You also need to build leveldown for every platform you want to run your electron app on and bundle it appropriately.

**Comment by sergiovilar** [comment] 2015-06-11 12:13
Okay guys, thank you so much. I'm dropping LevelDB and closing here.

**Closed** 2015-06-11 12:14 UTC

**Comment by MaxGfeller** [comment] 2016-03-16 10:29
I just stumbled upon this issue because it's one of the first Google search results for "electron + leveldown".

Just wanted to note that what @mafintosh said is totally correct; leveldown is being built against your local Node version on a `npm install`. That means if the Node version Electron uses isn't the same as your local one, it won't work.

You can rebuild `leveldown` as follows:

```
cd node_modules/leveldown
node-gyp node-gyp rebuild --target=0.37.2 --arch=x86 --dist-url=https://atom.io/download/atom-shell
```

Where `0.37.2` is the version of Electron you're running.

Also see [Electron's guide to Native Modules](http://electron.atom.io/docs/v0.37.2/tutorial/using-native-node-modules/).

**Comment by klausgao** [comment] 2016-03-27 11:04
@MaxGfeller Hi, could you please tell me your node version, npm version, leveldown version and some thing to notice? I tried all the guide and still failed.

**Comment by klausgao** [comment] 2016-03-27 11:05
@MaxGfeller I even can't install electron-rebuild. my env is win10 x64 + vs2015.

**Comment by klausgao** [comment] 2016-03-27 15:08
OK finally I solved. @MaxGfeller 's solution is almost right without some mistakes. now I write my own.
1. delete your whole node_modules.
2. npm install
3. get into node_modules/leveldown.
4. node-gyp rebuild --target=0.37.2 --arch=ia32 --dist-url=https://atom.io/download/atom-shell
notice it should be ia32, not x86.
BTW, don't know why, electron-rebuild always fail in my machine.

**Comment by Alxandr** [comment] 2017-05-01 19:50
I'm experiencing this problem using both `node-gyp` directly, `electron-rebuild` (and any other method I've found and tried). The result is the `no root element` error from msbuild.
