### ISSUE TITLE
Find key createReadStream

### ISSUE THREAD

**Issue by hanumanjiblog** [Level/leveldown#778] opened 2021-07-29 16:02 UTC
Not able to find specific part of the key "uid3" using createReadStream

const level = require('level')
const db = level('my-db')
setImmediate(async () => {
  await db.put('type:user:uid1', 'value')
  await db.put('type:user:uid2', 'value')
  await db.put('type:user:uid3', 'value')
// not working-
  db.createReadStream({ gte: '\xff:uid3' }).on('data', function (data) {
    console.log(data.key, '=', data.value)
  })
// not working-
 db.createReadStream({ gte: 'uid3' }).on('data', function (data) {
    console.log(data.key, '=', data.value)
  })
});

**Comment by vweevers** [comment] 2021-07-29 16:04
Duplicate of https://github.com/Level/level/issues/203.

**Closed by vweevers** 2021-07-29 16:04 UTC
Labels: duplicate

**Comment by hanumanjiblog** [comment] 2021-07-29 16:28
Why you not answering me & closing issue? if their any problem please discuss with me clearly.

**Comment by vweevers** [comment] 2021-07-29 18:10
I or someone else will answer when we have time and if we feel like it. Level is an open source project run by volunteers.

Personally I hesitated to answer because I don't want to just write your application for you, without teaching _why_ it works the way it does. An understanding of lexicographic order is essential for unlocking the power of level and I was unsure how to approach this, not knowing your background, or what documentation and prior art you looked at before opening a ticket. We lack a "getting started" guide on this topic, otherwise I would refer to that, but plenty of examples do exist.

I closed this because it's an exact duplicate of https://github.com/Level/level/issues/203. I stated that clearly. Please be aware that opening duplicate tickets or repeatedly asking for an answer will be perceived as spam and decrease the chance that you'll get an answer.

**Comment by hanumanjiblog** [comment] 2021-07-29 18:27
@vweevers I understand your words, Sorry for making duplicate issue.
but please please 🙏 tell me how to solve above problem ?
