### ISSUE TITLE
Feature request: add armv7 prebuilt 

### ISSUE THREAD

**Issue by austinfrey** [Level/leveldown#537] opened 2018-11-21 04:05 UTC
Would it be possible to have a prebuilt binary for raspberry pi/armv7? 

Thanks

**Comment by vweevers** [comment] 2018-11-21 07:09
Duplicate of #360

**Closed by vweevers** 2018-11-21 07:09 UTC

**Comment by austinfrey** [comment] 2018-11-28 16:58
eessh! sorry @vweevers should have been paying more attention to already open issues :/

**Comment by vweevers** [comment] 2018-11-28 17:00
No worries ❤️
